In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [3]:
#Dividindo arrays por parte (Split)

arrays_divididos = np.split(array, 3)
arrays_divididos

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
for i, value in enumerate(arrays_divididos):
    print(f"Parte {i + 1}-> {value}")

Parte 1-> [1 2]
Parte 2-> [3 4]
Parte 3-> [5 6]


In [5]:
#Criando um array 1D com temperaturas diárias de um mês(30 Dias)

temperaturas = np.array([22, 21, 23, 25, 20, 19, 21,
                         24, 26, 27, 25, 22,
                         20, 18, 19, 20, 21,
                         22, 23, 24, 25, 26,
                         27, 28, 29, 30, 29,
                         28, 27, 26, 25, 24])
temperaturas

array([22, 21, 23, 25, 20, 19, 21, 24, 26, 27, 25, 22, 20, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24])

In [6]:
#Dividindo as temperaturas em 4 semanas

semanas = np.split(temperaturas, 4)
semanas

[array([22, 21, 23, 25, 20, 19, 21, 24]),
 array([26, 27, 25, 22, 20, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28]),
 array([29, 30, 29, 28, 27, 26, 25, 24])]

In [7]:
for i, value in enumerate(semanas):
    print(f"Semana {i + 1}:{value}")

Semana 1:[22 21 23 25 20 19 21 24]
Semana 2:[26 27 25 22 20 18 19 20]
Semana 3:[21 22 23 24 25 26 27 28]
Semana 4:[29 30 29 28 27 26 25 24]


In [8]:
#Calcular a média das temperaturas por semana

medias_semanas = [np.mean(semana) for semana in semanas]
medias_semanas

[np.float64(21.875), np.float64(22.125), np.float64(24.5), np.float64(27.25)]

In [12]:
for i, value in enumerate(medias_semanas):
    print(f"Média da semana {i+1} : {value:.2f}Celcius")

Média da semana 1 : 21.88Celcius
Média da semana 2 : 22.12Celcius
Média da semana 3 : 24.50Celcius
Média da semana 4 : 27.25Celcius
