In [2]:
import numpy as np

In [4]:
array = np.array([ [10, 20 , 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [5]:
#Buscar o elemento na linha 1 , coluna 2
elemento = array[1, 2]
elemento

np.int64(60)

In [6]:
#Pegar os dados da primeira linha
linha_0 = array[0]
linha_0

array([10, 20, 30])

In [7]:
#acessando a coluna 1
coluna_1 = array[:, 1]
coluna_1

array([20, 50, 80])

In [8]:
#Fatiando para obter um subarray
#Linha 0 a 1 | Coluna 1 a 2
subarray = array [0:2 , 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [10]:
mascara = array > 50
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [11]:
elemento_maior_que_50 = array[mascara]
elemento_maior_que_50

array([60, 70, 80, 90])

In [12]:
#Modificando elemento linha 1 | Coluna 1
array[1, 1] = 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])