In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
#1- Iteração simples usando Loop for.
for linha in array:
    print(linha)

[1 2 3]
[4 5 6]
[7 8 9]


In [5]:
for linha in array:
    for valor in linha:
        print(valor, end= " ")

1 2 3 4 5 6 7 8 9 

In [6]:
#2- Usando o np.nditer para uma iteração mais eficiente.
for valor in np.nditer(array):
    print(valor, end=' ')

1 2 3 4 5 6 7 8 9 

In [7]:
#3- Iteração com condição.
for valor in np.nditer(array):
    if valor > 5:
        print(valor, end=' ')

6 7 8 9 

In [10]:
#4- Iteração com indices
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        print(f'Elemento na posição({i}, {j}):{array[i, j]}')

Elemento na posição(0, 0):1
Elemento na posição(0, 1):2
Elemento na posição(0, 2):3
Elemento na posição(1, 0):4
Elemento na posição(1, 1):5
Elemento na posição(1, 2):6
Elemento na posição(2, 0):7
Elemento na posição(2, 1):8
Elemento na posição(2, 2):9
